language: clojure
lein: 2.7.1
os:
  - linux
jdk:
  - oraclejdk8
notifications:
  email: false
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - chmod a+x scripts/ci/test.sh
script: scripts/ci/test.sh
cache:
  directories:
    - $HOME/.m2
    - node_modules
    - $(npm config get prefix)/node_modules
env:
  - PLATFORM=clj
  - PLATFORM=cljs_browser
  - PLATFORM=cljs_node

#use these for lumo
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - libstdc++-4.9-dev
