language: node_js
node_js:
  - 7
os:
  - linux
jdk:
  - oraclejdk8
notifications:
  email: false
addons:
  firefox: "49.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
install:
  - chmod a+x $TRAVIS_BUILD_DIR/scripts/ci/travis_install.sh
  - $TRAVIS_BUILD_DIR/scripts/ci/travis_install.sh
script:
  - sh -e /etc/init.d/xvfb start
  - boot autotest -p $PLATFORM -t $TARGET -o $OPT ${SELF_HOSTED:+ -s}
cache:
  directories:
    - $HOME/.m2
    - $HOME/.boot/cache/lib
    - $HOME/.boot/cache/bin
    - $TRAVIS_BUILD_DIR/node_modules
    - $(npm config get prefix)/node_modules
    - $TRAVIS_BUILD_DIR/lumo_cache
    - $TRAVIS_BUILD_DIR/dep_cache
env:
  global:
    - SLIMERJSLAUNCHER=$(which firefox)
    - DISPLAY=:99.0
    - BOOT_JVM_OPTIONS= |
      - client
      - XX:+TieredCompilation
      - XX:TieredStopAtLevel=1
      - Xmx2g
      - XX:+UseConcMarkSweepGC
      - XX:+CMSClassUnloadingEnabled
      - Xverify:none
  matrix:
    - PLATFORM=clj

    - PLATFORM=cljs TARGET=nodejs  OPT=none
    - PLATFORM=cljs TARGET=nodejs  OPT=simple
  # - PLATFORM=cljs TARGET=nodejs  OPT=advanced
    - PLATFORM=cljs TARGET=nodejs  OPT=none     SELF_HOSTED=true

    - PLATFORM=cljs TARGET=browser OPT=none
    - PLATFORM=cljs TARGET=browser OPT=simple
    - PLATFORM=cljs TARGET=browser OPT=advanced
  # - PLATFORM=cljs TARGET=browser OPT=none     SELF_HOSTED=true
