language: node_js
node_js:
  - 7
os:
  - linux
jdk:
  - oraclejdk8
notifications:
  email: false
addons:
  firefox: "49.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_install:
  - wget https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin
install:
  - boot
before_script:
  - chmod a+x scripts/ci/before_script.sh
  - scripts/ci/before_script.sh
script:
  - boot autotest -p $PLATFORM -t $TARGET -o $OPT ${SELF_HOSTED:+ -s}
cache:
  directories:
    - $HOME/.m2
    - $HOME/.boot/cache/lib
    - $HOME/.boot/cache/bin
    - node_modules
    - $(npm config get prefix)/node_modules
    - lumo_cache
    - slimerjs
env:
  global:
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
    - BOOT_JVM_OPTIONS= |
      - client
      - XX:+TieredCompilation
      - XX:TieredStopAtLevel=1
      - Xmx2g
      - XX:+UseConcMarkSweepGC
      - XX:+CMSClassUnloadingEnabled
      - Xverify:none
  matrix:
    - PLATFORM=clj

    - PLATFORM=cljs TARGET=nodejs  OPT=none
    - PLATFORM=cljs TARGET=nodejs  OPT=simple
  # - PLATFORM=cljs TARGET=nodejs  OPT=advanced
    - PLATFORM=cljs TARGET=nodejs  OPT=none     SELF_HOSTED=true

    - PLATFORM=cljs TARGET=browser OPT=none
    - PLATFORM=cljs TARGET=browser OPT=simple
    - PLATFORM=cljs TARGET=browser OPT=advanced
  # - PLATFORM=cljs TARGET=browser OPT=none     SELF_HOSTED=true
