language: clojure
lein: 2.7.1
before_script:
  - chmod a+x scripts/test.sh
script: scripts/test.sh
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
env:
  - PLATFORM=clj
  - PLATFORM=cljs_browser
  - PLATFORM=cljs_node
