language: clojure
lein: 2.7.1
os:
  - linux
jdk:
  - oraclejdk8
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
before_script:
  - npm install -g lumo-cljs
  - chmod a+x scripts/ci/test.sh
script: scripts/ci/test.sh
cache:
  directories:
    - $HOME/.m2
    - node_modules
    - $(npm config get prefix)/node_modules
    - lumo_cache
env:
  - PLATFORM=clj
  - PLATFORM=cljs TARGET=node    SELF_HOSTED=false OPT=none
  - PLATFORM=cljs TARGET=node    SELF_HOSTED=false OPT=simple
# - PLATFORM=cljs TARGET=node    SELF_HOSTED=false OPT=advanced
  - PLATFORM=cljs TARGET=node    SELF_HOSTED=true  OPT=none
# - PLATFORM=cljs TARGET=browser SELF_HOSTED=false OPT=simple
# - PLATFORM=cljs TARGET=browser SELF_HOSTED=false OPT=advanced
# - PLATFORM=cljs TARGET=browser SELF_HOSTED=false OPT=none
# - PLATFORM=cljs TARGET=browser SELF_HOSTED=true  OPT=none
