language: clojure
lein: 2.7.1
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_script:
  - chmod a+x scripts/ci/before_script.sh
  - scripts/ci/before_script.sh
script: scripts/ci/test.sh
cache:
  directories:
    - $HOME/.m2
    - node_modules
    - $(npm config get prefix)/node_modules
env:
  - PLATFORM=clj
  - PLATFORM=cljs_browser
  - PLATFORM=cljs_node
