language: clojure
lein: 2.7.1
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_install:
  - chmod a+x scripts/before_install.sh
  - scripts/before_install.sh
before_script:
  - chmod a+x scripts/before_script.sh
  - scripts/before_script.sh
script: scripts/test.sh
cache:
  directories:
    - $HOME/.m2
    - node_modules
env:
  - PLATFORM=clj
  - PLATFORM=cljs_browser
#  - PLATFORM=cljs_node
