language: java
os: linux
jdk: oraclejdk8
notifications:
  email: false
addons:
  firefox: "49.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
install:
  - mkdir -p $HOME/bin
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o $HOME/bin/boot
  - chmod a+x $HOME/bin/boot

  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

  - chmod a+x $TRAVIS_BUILD_DIR/scripts/ci/travis_install.sh
  - $TRAVIS_BUILD_DIR/scripts/ci/travis_install.sh
before_script:
  - boot -u
script:
  - sh -e /etc/init.d/xvfb start
  - boot show -d
  - boot test -p $PLATFORM -t $TARGET -o $OPT ${SELF_HOSTED:+ -s}
cache:
  directories:
    - $HOME/bin
    - $HOME/.m2
    - $HOME/.boot/cache/lib
    - $HOME/.boot/cache/bin
    - $TRAVIS_BUILD_DIR/node_modules
    - $(npm config get prefix)/node_modules
    - $TRAVIS_BUILD_DIR/lumo_cache
    - $TRAVIS_BUILD_DIR/dep_cache
env:
  global:
    - CACHE_DIR=$TRAVIS_BUILD_DIR/dep_cache
    - PATH=$CACHE_DIR/lumo:$CACHE_DIR/slimerjs:$CACHE_DIR/boot:$HOME/bin:$PATH
    - SLIMERJSLAUNCHER=$(which firefox)
    - DISPLAY=:99.0
    - BOOT_JVM_OPTIONS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx4g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"
  matrix:
    - PLATFORM=clj

    - PLATFORM=cljs TARGET=nodejs  OPT=none
  # - PLATFORM=cljs TARGET=nodejs  OPT=advanced
    - PLATFORM=cljs TARGET=nodejs  OPT=none     SELF_HOSTED=true

    - PLATFORM=cljs TARGET=browser OPT=none
    - PLATFORM=cljs TARGET=browser OPT=advanced
  # - PLATFORM=cljs TARGET=browser OPT=none     SELF_HOSTED=true
